name: omniscribe

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PYTHONDONTWRITEBYTECODE=1 # Запрещает Python генерировать __pycache__
      - PYTHONUNBUFFERED=1        # Немедленный вывод логов Python в консоль
      - DATABASE_URL=postgresql://user:password@db:5432/omniscribe
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=omniscribe
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: